/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tutorialproductos.vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tutorialproductos.entidades.Categoria;
import tutorialproductos.entidades.Producto;
import tutorialproductos.modelos.CategoriaData;
import tutorialproductos.modelos.ProductoData;

/**
 *
 * @author Usuario
 */
public class GestionProductos extends javax.swing.JFrame {
    
    private CategoriaData cd;
    private ProductoData pd;
    private DefaultTableModel modelo;
    private Producto productoElegido;
    

    /**
     * Creates new form Tablas1
     */
    public GestionProductos() {
        initComponents();
         modelo = new DefaultTableModel();
         cd = new CategoriaData();
         pd = new ProductoData();
         llenarCombos();
         desactivarCampos();
         armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jcbCategoria = new javax.swing.JComboBox<>();
        jlCategoria = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();
        jLCodigo = new javax.swing.JLabel();
        jLDescripcion = new javax.swing.JLabel();
        jLPrecio = new javax.swing.JLabel();
        jLCategoria2 = new javax.swing.JLabel();
        jcbCategoriaProducto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jtfDescripcion = new javax.swing.JTextField();
        jtfPrecio = new javax.swing.JTextField();
        jspStock = new javax.swing.JSpinner();
        jbtNuevo = new javax.swing.JButton();
        jbtGuardar = new javax.swing.JButton();
        jbtActualizar = new javax.swing.JButton();
        jbtBorrar = new javax.swing.JButton();
        jbtSalir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Gestion de Productos");

        jcbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCategoriaActionPerformed(evt);
            }
        });

        jlCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCategoria.setText("Categoria");

        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtProductos);

        jLCodigo.setText("Codigo");

        jLDescripcion.setText("Descripción");

        jLPrecio.setText("Precio");
        jLPrecio.setRequestFocusEnabled(false);

        jLCategoria2.setText("Categoria");

        jLabel2.setText("Stock");

        jtfCodigo.setToolTipText("");
        jtfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoFocusLost(evt);
            }
        });

        jtfDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDescripcionFocusLost(evt);
            }
        });

        jtfPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfPrecioFocusLost(evt);
            }
        });

        jbtNuevo.setText("Nuevo");
        jbtNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNuevoActionPerformed(evt);
            }
        });

        jbtGuardar.setText("Guardar");
        jbtGuardar.setEnabled(false);
        jbtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGuardarActionPerformed(evt);
            }
        });

        jbtActualizar.setText("Actualizar");
        jbtActualizar.setEnabled(false);
        jbtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtActualizarActionPerformed(evt);
            }
        });

        jbtBorrar.setText("Borrar");
        jbtBorrar.setEnabled(false);

        jbtSalir.setText("Salir");
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCodigo)
                            .addComponent(jLDescripcion)
                            .addComponent(jLPrecio)
                            .addComponent(jLCategoria2)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbCategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jspStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jbtNuevo)
                        .addGap(148, 148, 148)
                        .addComponent(jbtGuardar)
                        .addGap(45, 45, 45)
                        .addComponent(jbtActualizar)
                        .addGap(32, 32, 32)
                        .addComponent(jbtBorrar)
                        .addGap(30, 30, 30)
                        .addComponent(jbtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(220, 220, 220)
                            .addComponent(jlCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCategoria))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCodigo)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDescripcion)
                    .addComponent(jtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPrecio)
                    .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCategoria2)
                    .addComponent(jcbCategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jspStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtNuevo)
                    .addComponent(jbtGuardar)
                    .addComponent(jbtActualizar)
                    .addComponent(jbtBorrar)
                    .addComponent(jbtSalir))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNuevoActionPerformed
        activarCampos();
        jbtGuardar.setEnabled(true);
    }//GEN-LAST:event_jbtNuevoActionPerformed

    private void jtfCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoFocusLost
        // TODO add your handling code here:
        String val = "[0-9]*"; //Expresiones Regulares
        
        //Valida si no es un numero
        if(!jtfCodigo.getText().matches(val)){
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero");
            jtfCodigo.requestFocus();
        }
    }//GEN-LAST:event_jtfCodigoFocusLost

    private void jtfDescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDescripcionFocusLost
        // TODO add your handling code here:
        if(jtfDescripcion.getText().length()==0){
            JOptionPane.showMessageDialog(this, "La descripcion no debe estar vacia");
            jtfDescripcion.requestFocus();
        }
    }//GEN-LAST:event_jtfDescripcionFocusLost

    private void jtfPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfPrecioFocusLost
        // TODO add your handling code here:
        try{
            String precio = jtfPrecio.getText();
            double prec = Double.parseDouble(precio);
        }catch(NumberFormatException nf){
            JOptionPane.showMessageDialog(this, "Debe ingresar un precio válido");
            jtfPrecio.requestFocus();
        }
    }//GEN-LAST:event_jtfPrecioFocusLost

    private void jbtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGuardarActionPerformed
        // TODO add your handling code here:
        Producto pn = new Producto();
        pn.setCodigo(Integer.parseInt(jtfCodigo.getText()));
        pn.setDescripcion(jtfDescripcion.getText());
        pn.setPrecio(Double.parseDouble(jtfPrecio.getText()));
        pn.setCategoria((Categoria)jcbCategoriaProducto.getSelectedItem());
        
        pd.guardarProducto(pn);
        limpiarCampos();
        desactivarCampos();
        jbtGuardar.setEnabled(false);
        
    }//GEN-LAST:event_jbtGuardarActionPerformed

    private void jcbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCategoriaActionPerformed
        // TODO add your handling code here:
        llenarTabla();
    }//GEN-LAST:event_jcbCategoriaActionPerformed

    private void jtProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProductosMouseClicked
        // TODO add your handling code here:
        jbtActualizar.setEnabled(true);
        jbtBorrar.setEnabled(true);
        int filaElegida = jtProductos.getSelectedRow();//toma la fila seleccionada en la tabla
        
        if(filaElegida != -1){
            int idProducto = (Integer)jtProductos.getValueAt(filaElegida,0);
            int codigo = (Integer)jtProductos.getValueAt(filaElegida, 1);
            String descripcion = (String)jtProductos.getValueAt(filaElegida, 2);
            double precio = (Double)jtProductos.getValueAt(filaElegida, 3);
            Categoria catTabla = (Categoria)jtProductos.getValueAt(filaElegida, 4);
            int stock = (Integer)jtProductos.getValueAt(filaElegida, 5);
        
        jtfCodigo.setText(codigo+"");
        jtfDescripcion.setText(descripcion);
        jtfPrecio.setText(precio+"");
        jcbCategoriaProducto.setSelectedItem(catTabla);
        jspStock.setValue(stock);
        
        activarCampos();
        productoElegido = new Producto();
        productoElegido.setIdProducto(idProducto);
        productoElegido.setCodigo(codigo);
        productoElegido.setDescripcion(descripcion);
        productoElegido.setPrecio(precio);
        productoElegido.setCategoria(catTabla);
        productoElegido.setStock(stock);
           
        }
    }//GEN-LAST:event_jtProductosMouseClicked

    private void jbtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtActualizarActionPerformed
        // TODO add your handling code here:
        //parseo los datos obtenidos de los campos
        int codigo = Integer.parseInt(jtfCodigo.getText());
        String descripcion = jtfDescripcion.getText();
        double precio = Double.parseDouble(jtfPrecio.getText());
        Categoria catNueva = (Categoria)jcbCategoriaProducto.getSelectedItem();
        int stock = (Integer)jspStock.getValue();
        
        //seteo el producto elegido con los atributos cargados en los campos
        productoElegido.setCodigo(codigo);
        productoElegido.setDescripcion(descripcion);
        productoElegido.setPrecio(precio);
        productoElegido.setStock(stock);
        productoElegido.setCategoria(catNueva);
        
        //llamo a ProductoData y modificoel producto
        pd.modificarProducto(productoElegido);
        productoElegido = null;
        limpiarCampos(); //limpio los campos
        desactivarCampos();//los desactivo
        llenarTabla(); // y cargo nuevamente en la tabla el producto actualizado
        jbtActualizar.setEnabled(false); //desactivo el boton actulizar
    }//GEN-LAST:event_jbtActualizarActionPerformed

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbtSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionProductos().setVisible(true);
            }
        });
    }
    private void llenarCombos(){
        
        for(Categoria c:cd.obtenerCategorias()){
            jcbCategoria.addItem(c);
            jcbCategoriaProducto.addItem(c);
        }
    }
    private void activarCampos(){
        jtfCodigo.setEnabled(true);
        jtfDescripcion.setEnabled(true);
        jtfPrecio.setEnabled(true);
        jcbCategoriaProducto.setEnabled(true);
        jspStock.setEnabled(true);
    }  
     private void desactivarCampos(){
        jtfCodigo.setEnabled(false);
        jtfDescripcion.setEnabled(false);
        jtfPrecio.setEnabled(false);
        jcbCategoriaProducto.setEnabled(false);
        jspStock.setEnabled(false);
    }
     private void limpiarCampos(){
        jtfCodigo.setText("");
        jtfDescripcion.setText("");
        jtfPrecio.setText("");
        jcbCategoriaProducto.setSelectedIndex(0);
        jspStock.setValue(0);
     }
     private void armarCabecera(){
         ArrayList<Object>columnas = new ArrayList<Object>();
         columnas.add("ID");
         columnas.add("Codigo");
         columnas.add("Descripcion");
         columnas.add("Precio");
         columnas.add("Categoria");
         columnas.add("Stock");
         
         for(Object it:columnas){
             modelo.addColumn(it);
         }
         jtProductos.setModel(modelo);
     }
     private void llenarTabla(){
         borrarFilas();
         Categoria elegida = (Categoria)jcbCategoria.getSelectedItem();//Se crea un objeto del tipo Categoria
         if(elegida != null){
             
             for(Producto p:pd.obtenerProductos()){
                 if(p.getCategoria().equals(elegida)){
                     modelo.addRow(new Object[]{p.getIdProducto(),p.getCodigo(),p.getDescripcion(),p.getPrecio(),p.getCategoria(),p.getStock()});
                 }
             }
         }
     }
     private void borrarFilas(){
         int a = modelo.getRowCount()-1;
         
         for(int i = a;i >0;i--){
             modelo.removeRow(i); //elimina filas
         }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLCategoria2;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtActualizar;
    private javax.swing.JButton jbtBorrar;
    private javax.swing.JButton jbtGuardar;
    private javax.swing.JButton jbtNuevo;
    private javax.swing.JButton jbtSalir;
    private javax.swing.JComboBox<Categoria> jcbCategoria;
    private javax.swing.JComboBox<Categoria> jcbCategoriaProducto;
    private javax.swing.JLabel jlCategoria;
    private javax.swing.JSpinner jspStock;
    private javax.swing.JTable jtProductos;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfDescripcion;
    private javax.swing.JTextField jtfPrecio;
    // End of variables declaration//GEN-END:variables
}
